services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    environment:
      - DEBUG=1
    depends_on:
      - db

  db:
    image: docker.arvancloud.ir/postgres:15
    environment:
      POSTGRES_DB: appointment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  media_volume:
  static_volume: