services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: docker.arvancloud.ir/postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  media_volume:
  static_volume: