# Generated by Django 4.2.24 on 2025-09-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0002_remove_doctor_created_at_doctor_image'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=5000)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patient.patient')),
                ('visit_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctors.visittime')),
            ],
        ),
    ]
