# Generated by Django 4.2.24 on 2025-09-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_created_at_doctor_image'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='visit_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.visittime'),
        ),
    ]
