# Generated by Django 4.2.24 on 2025-09-24 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_num', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999999)])),
                ('inventory', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999999999)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
