# Generated by Django 4.2.24 on 2025-09-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_created_at'),
        ('doctors', '0002_remove_doctor_created_at_doctor_image'),
    ]

    operations = [
    ]
